apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plugin-dca
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: traefik
  tls:
    - secretName: plugin-dca-tls
      hosts:
        - plugin-dca-send.lb.services-dev.1conf.com
        - plugin-dca-swap.lb.services-dev.1conf.com
  rules:
    - host: plugin-dca-send.lb.services-dev.1conf.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-send
                port:
                  number: 80
    - host: plugin-dca-swap.lb.services-dev.1conf.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-swap
                port:
                  number: 80
