apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plugin-dca
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web-internal
spec:
  ingressClassName: traefik
  rules:
    - host: dca-send.lb-1.plugins-cluster.nbitslabs.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-send
                port:
                  number: 80
    - host: dca-swap.lb-1.plugins-cluster.nbitslabs.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-swap
                port:
                  number: 80
