apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-indexer
  labels:
    app: tx-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-indexer
  template:
    metadata:
      labels:
        app: tx-indexer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tx-indexer
          image: ghcr.io/vultisig/app-recurring/tx_indexer:dev-5bdc6c048773896a273e7fa46d98b8da6e660b68
          command: ["/app/main"]
          ports:
            - containerPort: 80
              name: health
            - containerPort: 8088
              name: metrics
          env:
            - name: HEALTHPORT
              value: "80"
            - name: BASE_RPC_ETHEREUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: ethereum
            - name: BASE_RPC_ARBITRUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: arbitrum
            - name: BASE_RPC_AVALANCHE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: avalanche
            - name: BASE_RPC_BSC_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: bsc
            - name: BASE_RPC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: base
            - name: BASE_RPC_BLAST_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: blast
            - name: BASE_RPC_OPTIMISM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: optimism
            - name: BASE_RPC_POLYGON_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: polygon
            - name: BASE_RPC_XRP_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: xrp
            - name: BASE_INTERVAL
              value: "30s"
            - name: BASE_ITERATIONTIMEOUT
              value: "30s"
            - name: BASE_MARKLOSTAFTER
              value: "2h"
            - name: BASE_CONCURRENCY
              value: "5"
            - name: BASE_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_PORT
              value: "8088"
            - name: LOGFORMAT
              value: "json"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
