apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: worker
          image: busybox
          command: ["/app/main"]
          ports:
            - containerPort: 80
              name: health
            - containerPort: 8088
              name: metrics
          env:
            - name: HEALTHPORT
              value: "80"
            - name: VAULTSERVICE_RELAY_SERVER
              valueFrom:
                configMapKeyRef:
                  name: relay
                  key: url
            - name: VAULTSERVICE_LOCALPARTYPREFIX
              value: "vultisig-dca-0000"
            - name: VAULTSERVICE_ENCRYPTIONSECRET
              valueFrom:
                secretKeyRef:
                  name: encryption
                  key: secret
            - name: VAULTSERVICE_DOSETUPMSG
              value: "true"
            - name: VERIFIER_URL
              valueFrom:
                configMapKeyRef:
                  name: verifier
                  key: url
            - name: VERIFIER_SENDTOKEN
              valueFrom:
                secretKeyRef:
                  name: verifier
                  key: send-token
            - name: VERIFIER_SWAPTOKEN
              valueFrom:
                secretKeyRef:
                  name: verifier
                  key: swap-token
            - name: VERIFIER_PARTYPREFIX
              valueFrom:
                configMapKeyRef:
                  name: verifier
                  key: party-prefix
            - name: RPC_ETHEREUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: ethereum
            - name: RPC_ARBITRUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: arbitrum
            - name: RPC_AVALANCHE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: avalanche
            - name: RPC_BSC_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: bsc
            - name: RPC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: base
            - name: RPC_BLAST_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: blast
            - name: RPC_OPTIMISM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: optimism
            - name: RPC_POLYGON_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: polygon
            - name: RPC_XRP_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: xrp
            - name: ONEINCH_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: oneinch
                  key: base-url
            - name: RPC_SOLANA_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: solana
            - name: RPC_ZKSYNC_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: zksync
            - name: RPC_CRONOS_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: cronos
            - name: THORCHAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: thorchain
                  key: url
            - name: BTC_BLOCKCHAIRURL
              valueFrom:
                configMapKeyRef:
                  name: blockchair
                  key: url
            - name: ZEC_BLOCKCHAIRURL
              valueFrom:
                configMapKeyRef:
                  name: blockchair
                  key: url
            - name: MAYACHAIN_URL
              valueFrom:
                configMapKeyRef:
                  name: mayachain
                  key: url
            - name: SOLANA_JUPITERAPIURL
              valueFrom:
                configMapKeyRef:
                  name: solana
                  key: jupiter-api-url
            - name: BLOCKSTORAGE_HOST
              valueFrom:
                configMapKeyRef:
                  name: minio
                  key: host
            - name: BLOCKSTORAGE_REGION
              valueFrom:
                configMapKeyRef:
                  name: minio
                  key: region
            - name: BLOCKSTORAGE_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root-user
            - name: BLOCKSTORAGE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root-password
            - name: BLOCKSTORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: minio
                  key: bucket
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: uri
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_PORT
              value: "8088"
            - name: LOGFORMAT
              value: "json"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
